statements/urls.py
from django.urls import path
from . import views

app_name = 'statements'

urlpatterns = [
    path('', views.index, name='index'),
    path('leave/', views.leave, name='leave'),
    path('add_leave/', views.add_leave, name='add_leave'),
    path('delete_leave/<int:leave_id>', views.delete_leave, name='delete_leave'),
    path('teachers/', views.teachers_name, name='teachers_name'),
]

teachers_statements/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('statements.urls')),
]

users/urls.py
from django.urls import path, include

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
]

statements/models.py
from django.db import models
from django.contrib.auth.models import User
from .widgets import DatePickerInput
from statements import widgets

# Create your models here.
class TeachersName(models.Model):
    name = models.CharField(max_length=200)
    
class HalaqaName(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class HalaqaType(models.Model):
    type = models.CharField(max_length=200)

    def __str__(self):
        return self.type

class HalaqaCriteria(models.Model):
    criteria = models.CharField(max_length=200)

    def __str__(self):
        return self.criteria

class HalaqaTime(models.Model):
    time = models.CharField(max_length=200)

    def __str__(self):
        return self.time
    
class Teachers(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    general_id = models.CharField(max_length=200, blank=True)
    financial_id = models.CharField(max_length=200, blank=True)
    halaqa_name = models.ForeignKey(HalaqaName, on_delete=models.PROTECT)
    halaqa_type = models.ForeignKey(HalaqaType, on_delete=models.DO_NOTHING)

    class Meta:
        verbose_name_plural = 'teachers'
    def __str__(self):
        return self.name

class Leave(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    halaqa_name = models.ForeignKey(HalaqaName, on_delete=models.PROTECT)
    halaqa_type = models.ForeignKey(HalaqaType, on_delete=models.DO_NOTHING)
    date_of_leave = models.DateField()
    date_of_return = models.DateField()

    def __str__(self):
        return str(self.owner)

users/models.py
from django.db import models

# Create your models here.

statements/forms.py
from django import forms
from .models import Leave
from .widgets import DatePickerInput

class LeaveForm(forms.ModelForm):
    class Meta:
        model = Leave
        fields = ['halaqa_name', 'halaqa_type', 'date_of_leave', 'date_of_return']
        widgets = {'date_of_leave' : DatePickerInput(), 'date_of_return' : DatePickerInput(),}

statements/views.py
from django.shortcuts import redirect, render
from .models import Teachers, Leave
from .forms import LeaveForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
# Create your views here.

def index(request):
    return render(request, 'index.html')

def teachers_name(request):
    teacher_names = Teachers.objects.all()
    context = {'teacher_names':teacher_names}
    return render(request, 'teachers_name.html', context)

@login_required
def leave(request):
    teacher = Teachers.objects.get(owner=request.user)
    leave = Leave.objects.filter(owner=request.user)
    context = {'leave':leave, 'teacher':teacher}
    return render(request, 'leave.html', context)

@login_required
def add_leave(request):
    #owner = request.user
    #owner_id = owner.id
    #teacher = TeachersName.objects.get(owner_id=owner_id)
    teacher = Teachers.objects.get(owner=request.user)
    if request.method != 'POST':
        form = LeaveForm()

    else:
        form = LeaveForm(data=request.POST)
        if form.is_valid():
            new_leave = form.save(commit=False)
            new_leave.owner = request.user
            new_leave.bfs_task_duration = abs((new_leave.date_of_leave - new_leave.date_of_return).days)
            new_leave.save()
            return redirect('statements:leave')
    context = {'form': form, 'teacher': teacher}
    return render(request, 'add_leave.html', context)

@login_required
def delete_leave(request, leave_id):
    leave = Leave.objects.get(id=leave_id)
    leave.delete()
    return redirect('statements:leave')

users/views.py
from django.shortcuts import render

# Create your views here.

statements/templates/add_leave.html
{% extends 'base.html' %}

{% block content %}

<p>اسم المعلم: {{ teacher }}</p>
<p>الرقم العام: {{ teacher.general_id }}</p>
<form action="{% url 'statements:add_leave' %}" method="post">
{% csrf_token %}
{{ form.as_p }}
<button name="submit">Submit</button>
</form>

{% endblock content %}

statements/templates/base.html
<!DOCTYPE html>
<html dir="rtl" lang="ar">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>برنامج شؤون المشرفين والمعلمين</title>
    <center><h2>برنامج شؤون المشرفين والمعلمين</h2></center>
    
</head>
<p><a href="{% url 'statements:index' %}">الصفحة الرئيسية</a></p>
{% if user.is_authenticated %}
مرحبا/ {{ user.first_name }} -
<a href="{% url 'users:logout' %}">تسجيل الخروج</a>
<p></p>
<a href="{% url 'statements:teachers_name' %}">اسماء المعلمين</a> -
<a href="{% url 'statements:leave' %}">اجازاتي</a>
{% else %}
<a href="{% url 'users:login' %}">تسجيل الدخول</a>
{% endif %}
<body>
    <p></p>
    {% block content %}
    {% endblock content %}
</body>
</html>

statements/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h2>الصفحة الرئيسية</h2>

{% endblock content %}

statements/templates/leave.html
{% extends 'base.html' %}

{% block content %}
<ul>
        <p>اسم المعلم: {{ teacher }}</p>
        <p>اسم الحلقة: {{ teacher.halaqa_name }}</p>
        <p>فئة الحلقة: {{ teacher.halaqa_type }}</p>
    {% for vac in leave %}
    <li>
        <p>تاريخ المغادرة: {{ vac.date_of_leave }}</p>
        <p>تاريخ العودة: {{ vac.date_of_return }}</p>
        <p><a href="{% url 'statements:delete_leave' vac.id %}">Delete leave</a></p>
    </li>
    {% endfor %}
</ul>


<a href="{% url 'statements:add_leave' %}">طلب اجازة</a>
{% endblock content %}

statements/templates/teachers_name.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <tr>
            <th>الرقم العام</th>
            <th>الرقم المالي</th>
            <th>الاسم</th>
            <th>الحلقة</th>
            <th>الفئة</th>
        </tr>
        {% for item in teacher_names %}
        <tr>
            <td>{{ item.financial_id }}</td>
            <td>{{ item.general_id }}</td>
            <td>{{ item.name }}</td>
            <td>{{ item.halaqa_name }}</td>
            <td>{{ item.halaqa_type }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock content %}